@startuml
(*)-->initialization
if input.student
    -->[true] "find xclass where name = input.field"
    if xclass != null
        -->[true] "find studentJ where number = input.number && id != input.id"
        if studentJ != null
            --> [true] ==RouteF==
            --> return false
            --> (*)
        else
            --> [false] call update user
            --> find student
            if student == null
                --> [true] student.create
                --> call update student
            else
                --> [false] call update student
            endif
            --> ==RouteT==
            --> return true
            --> (*)
        endif
    else
        --> ==RouteF==
    endif
else
    --> [false] calculate adminType
    if adminType != (school | superAdmin)
        --> [true] "find college where name = input.field"
        --> ==Route1==
    else
        --> [false] ==Route1==
    endif
    if adminType != (superAdmin | inValid)
        --> [true] ==RouteF==
    else
        if college != null | adminType.pass
            --> [true] "find teacherJ where number = input.number && id != input.id"
            if teacherJ != null
                --> [true] ==RouteF==
            else
                --> [false] ==Route2==
            endif
            --> call update user2
            --> find teacher
            if teacher == null
                --> [true] teacher.create
                --> ==Route3==
            else
                --> [false] ==Route3==
            endif
            if college != null
                --> [true] update teacher.collegeId
                --> ==Route4==
            else
                --> [false] ==Route4==
            endif
            if adminType
                --> update admin
                --> ==RouteT==
            else
                --> [false] call update teacher
                --> ==RouteT==
            endif
        else
            --> [false] ==RouteF==
        endif
    endif
endif


@enduml