POST http://{{host}}/api/college
Content-Type: application/x-www-form-urlencoded

action=get

###

POST http://{{host}}/api/college
Content-Type: application/x-www-form-urlencoded

action=add&name=测试学院1

###



